# 20190703 - init 
# headless x11:
#  https://docs.travis-ci.com/user/gui-and-headless-browsers/
#  https://github.com/pytest-dev/pytest-qt/blob/master/.travis.yml

language: python
python: "3.7"
sudo: required
dist: xenial 

env:
   global:
      - DEPS="pytest pytest-qt psycopg2-binary pyesql pytest-pgsql git+https://github.com/LabNeuroCogDevel/LNCDcal.py pyqt5"
      - DISPLAY=":99"

install:
  - |
    # Xvfb / window manager
    sudo apt-get update
    sudo apt-get install -y xvfb # herbstluftwm
    # 
    # https://github.com/travis-ci/travis-ci/issues/6747
    sudo apt-get install -qq libegl1-mesa
    # Setup python
    pip install -U pip pytest
    pip install ${DEPS}
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset

before_script:
 - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
 - sleep 1
 # - "herbstluftwm &"
 # - sleep 1

script:
  # for debugging see current loc and settings
  # try testing qt and sql by themselves.
  - pwd
  - ls
  - which python
  - which pytest
  - pytest tests/ui/test_gui_search.py -s
  - pytest tests/db/test_cur_user.py -s
  - pytest -v tests
