# 20190703 - init 
# headless x11:
#  https://docs.travis-ci.com/user/gui-and-headless-browsers/
#  https://github.com/pytest-dev/pytest-qt/blob/master/.travis.yml

language: python
python: "3.7"
sudo: required
dist: xenial 

env:
   global:
      - DEPS="pytest pytest-qt psycopg2-binary pyesql pytest-pgsql git+https://github.com/LabNeuroCogDevel/LNCDcal.py pyqt5"
      - DISPLAY=":99"
      - QT_DEBUG_PLUGINS=1

install:
  - |
    # Xvfb / window manager
    sudo apt-get update
    sudo apt-get install -y xvfb libqt5gui5 # herbstluftwm
    
    # > qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
    # QT_DEBUG_PLUGINS=1
    # > cannot load library /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so
    # 20190705 -- local system
    #  apt-file search /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
    #  libqt5gui5: /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxc.so

    # Setup python
    pip install -U pip pytest
    pip install ${DEPS}
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset

before_script:
 # needed so tests can find code
 - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
 - sleep 1

script:
  - pytest -v tests
