# 20190703 - init 
# headless x11: https://docs.travis-ci.com/user/gui-and-headless-browsers/

language: python
python: "3.6"
sudo: required
dist: trusty

env:
   global:
      - DEPS="pytest pytest-qt psycopg2-binary pyesql pytest-pgsql git+https://github.com/LabNeuroCogDevel/LNCDcal.py pyqt5"
      - DISPLAY=":99"

install:
  - |
    # Xvfb / window manager
    sudo apt-get update
    sudo apt-get install -y xvfb # herbstluftwm
    # Setup python
    pip install -U pip
    pip install ${DEPS}

before_script:
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
 - sleep 3
 # - "herbstluftwm &"
 # - sleep 1

script:
  - "pytest -v tests"
