# 20190703 - init 
# cribbed from from pytest-qt's .travis.yml

language: python
python: "3.6"
sudo: required
dist: trusty

env:
   global:
      DEPS="pytest pytest-qt psycopg2-binary pyesql pytest-pgsql git+https://github.com/LabNeuroCogDevel/LNCDcal.py pyqt5"

install:
  - |
    # Xvfb / window manager
    sudo apt-get update
    sudo apt-get install -y xvfb herbstluftwm
    # courtesy of https://github.com/astropy/ci-helpers/blob/master/travis/setup_conda_linux.sh
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
    # Setup python
    pip install -U pip
    pip install ${DEPS}

before_script:
 - "herbstluftwm &"
 - sleep 1

script:
  - "pytest -v tests"
